spring:
  application:
    name: Bank-Management-System-ZUUL
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bms  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka;   
server.port: 8765
Zuul:
  routes:
    Bank-Management-System:
      url: http://localhost:8095
    Loan-Management-System:
      url: http://localhost:8090
